Repository yazatime/I_know, pull requests merged in 2024-07, with the labels that each got.

#2 Feat/#1
  I_know/board/TipBoardService
  I_know/credit/CreditService.md
  I_know/member/user_login/UserLogin.md
  I_know/member/user_signup/UserJoin.md
  I_know/tip/TipPostService
Labels: FEAT

#9 Feature/tip
  I_know/tip/TipPostService
  I_know/tip/TipPostService/Tipcomment/commentdelete.md
  I_know/tip/TipPostService/Tipcomment/commentmodify.md
  I_know/tip/TipPostService/Tipcomment/commentwrite.md
  I_know/tip/TipPostService/Tiphits.md
  I_know/tip/TipPostService/Tiplike.md
  I_know/tip/Tipdelete.md
  I_know/tip/Tipmodify.md
  I_know/tip/Tipwrite.md
  I_know/tip/managermark.md
Labels: FEAT

#12 게시판 기능 구현 완료
  I_know/board/QuestionDelete.md
  I_know/board/QuestionInsert.md
  I_know/board/QuestionModify.md
  I_know/board/QuestionReplyDelete.md
  I_know/board/QuestionReplyInsert.md
  I_know/board/QuestionReplyModify.md
  I_know/board/QuestionReplyReport.md
  I_know/board/QuestionReport.md
  I_know/board/TipBoardService
Labels: FEAT

#14 [FEAT] pullrequest template 파일 추가
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: FEAT

#31 Feat/#25
  I_know/tip/ManagerMark/ManagerMark.md
  I_know/tip/TipDeleteService/TipDelete.md
  I_know/tip/TipGetService/TipCommentService/TipCommentDelete.md
  I_know/tip/TipGetService/TipCommentService/TipCommentModify.md
  I_know/tip/TipGetService/TipCommentService/TipCommentPost.md
  I_know/tip/TipHitsService/TipHits.md
  I_know/tip/TipLikeService/TipLike.md
  I_know/tip/TipModifyService/TipModify.md
  I_know/tip/TipPostService/TipPost.md
  I_know/tip/TipPostService/Tipcomment/commentdelete.md
  I_know/tip/TipPostService/Tipcomment/commentmodify.md
  I_know/tip/TipPostService/Tipcomment/commentwrite.md
  I_know/tip/TipPostService/Tiphits.md
  I_know/tip/TipPostService/Tiplike.md
  I_know/tip/Tipdelete.md
  I_know/tip/Tipmodify.md
  I_know/tip/Tipwrite.md
  I_know/tip/managermark.md
Labels: ISSUE

#34 Feat/#33 tip 부분 삭제
  I_know/credit/change.md
  I_know/credit/credit.md
  I_know/tip/payment/on&on/on.md
  I_know/tip/payment/payback/account.md
  I_know/tip/transaction/change/record.md
  I_know/tip/transaction/post/on.md
  I_know/tip/transaction/post/select.md
Labels: FEAT

#35 Feat/#32
  I_know/tip/TipGetService/TipHitsService/TipHits.md
  I_know/tip/TipGetService/TipLikeService/TipLike.md
Labels: ISSUE

#37 Feat/#36
  I_know/member/admin/admin_member/GetMember.md
  I_know/member/admin/admin_member/get_member/GetMember.sql
  I_know/member/admin/admin_member/get_member/GetMemberList.sql
  I_know/member/admin/admin_member/get_question/GetQuestionContent.sql
  I_know/member/admin/admin_member/get_tip/GetTipContent.sql
Labels: FEAT, REFACTOR

#40 Feat/#39
  I_know/board/Delete/QuestionDelete.md
  I_know/board/Insert/QuestionInsert.md
  I_know/board/Modify/QuestionModify.md
  I_know/board/Reply/Delete/QuestionReplyDelete.md
  I_know/board/Reply/Insert/QuestionReplyInsert.md
  I_know/board/Reply/Modify/QuestionReplyModify.md
  I_know/board/Reply/Report/QuestionReplyReport.md
  I_know/board/Report/QuestionReport.md
  I_know/qna/answer/Answer_delete.sql
  I_know/qna/answer/Answer_insert.sql
  I_know/qna/answer/Answer_read.sql
  I_know/qna/answer/Answer_update.sql
  I_know/qna/question/Question_delete.sql
  I_know/qna/question/Question_insert.sql
  I_know/qna/question/Question_modify.sql
  I_know/qna/question/Question_read.sql
Labels: FEAT

#42 파일 생성 후 sql 옮기기
  I_know/qna/answer/delete/Answer_delete.sql
  I_know/qna/answer/insert/Answer_insert.sql
  I_know/qna/answer/read/Answer_read.sql
  I_know/qna/answer/update/Answer_update.sql
  I_know/qna/question/delete/Question_delete.sql
  I_know/qna/question/insert/Question_insert.sql
  I_know/qna/question/modify/Question_modify.sql
  I_know/qna/question/read/Question_read.sql
Labels: FEAT

#48 Feat/#47
  I_know/member/admin/admin_cash/CashManage.md
  I_know/member/admin/admin_cash/modify_cash/ModifyUserCash.sql
  I_know/member/admin/admin_member/DelMember.md
  I_know/member/admin/admin_member/SetMember.md
Labels: FEAT

#52 Feat/#51
  I_know/member/admin/admin_category/BoardCheck.md
  I_know/member/admin/admin_category/BoardHide.md
  I_know/member/admin/admin_category/BoardLevel.md
  I_know/member/admin/admin_category/delete_category/DeleteCategoryCode.sql
  I_know/member/admin/admin_category/get_category/GetCategoryCode.sql
  I_know/member/admin/admin_category/modify_category/ModifyCategoryCode.sql
  I_know/member/admin/admin_category/post_category/PostCategoryCode.sql
Labels: FEAT

#54 Feat/#53
  I_know/item/item_cash/iknow_cashChcek.sql
  I_know/item/item_cash/iknow_remainCash.sql
  I_know/item/item_cash/iknow_userCashType.sql
  I_know/item/item_shop/iknow_itemshop.sql
  I_know/item/item_user/iknow_userItem.sql
Labels: FEAT

#56 Feat/#55
  I_know/admin_item/admin_itemAdd/iknow_itemAdd_admin.sql
  I_know/admin_item/admin_itemDel/iknow_itemDel_admin.sql
  I_know/admin_item/admin_itemGet/iknow_itemGet_admin.sql
  I_know/admin_item/admin_itemUpdate/iknow_itemUpdate_admin.sql
Labels: FEAT

#60 #59 온 충전 시 잔량 확인 기능 수정 완료
  I_know/item/item_cash/iknow_cashChcek.sql
Labels: REFACTOR

#62 신고, 정지, 기능 추가
  I_know/report/report/iknow_report.sql
Labels: FEAT

#65 첨부파일 내용 삭제
  I_know/qna/question/modify/Question_modify.sql
Labels: REFACTOR

#68 질문글 삭제 기능 수정
  I_know/qna/question/delete/Question_delete.sql
Labels: REFACTOR

#66 Refactor/#63
  I_know/item/item_cash/iknow_remainCash.sql
Labels: REFACTOR

#70 답변글 조회, 수정, 삭제 기능
  I_know/qna/answer/delete/Answer_delete.sql
  I_know/qna/answer/read/Answer_read.sql
  I_know/qna/answer/update/Answer_update.sql
Labels: REFACTOR

#72 Refactor/#71
  I_know/tip/TipPostReply/create/tipPostReply_create.sql
  I_know/tip/TipPostReply/delete/tipPostReply_delete.sql
  I_know/tip/TipPostReply/update/tipPostReply_update.sql
  I_know/tip/TipPostService/delete/TipPost_delete.sql
  I_know/tip/TipPostService/insert/TipPost_insert.sql
  I_know/tip/TipPostService/read/TipPost_select.sql
  I_know/tip/TipPostService/update/TipPost_update.sql
Labels: REFACTOR

#74 메인 페이지 웹 배너 기능
  I_know/main_page/웹 배너 조회.sql
Labels: FEAT

#76 메인 페이지 TIP 10 조회
  I_know/main_page/TIP 10 조회.sql
Labels: FEAT

#78 메인 페이지 TIP 게시판 인기 순 조회 기능
  I_know/main_page/TIP 게시판 인기 순 조회.sql
Labels: FEAT

#80 메인 페이지 게시판 최신글 조회
  I_know/main_page/게시판 최신글 조회.sql
Labels: FEAT
